### PR TITLE
How to use section revamp

### LINKED ISSUE #165: How to use section revamp
1. 'How to use' section seems to me too prominent - perhaps the header there should be smaller and less 'outstanding'
2. It should use the same style as other sections.

image

### PR DESCRIPTION
**Pull request by rosolowski**
Fixes: #165 
New "How to use FIBO Viewer" style:
image

### CODE REVIEW

**Comment by mereolog** [comment]
I would make this section even smaller.
What do the other developers think? @dasawanaka @patrycjamia @rr-adam

**Comment by dasawanaka** [comment]
The margin can be reduced, it seems too large and on the similar colored div above it look smaller(search box)

**Comment by rosolowski** [comment]
Reduced margins:
image

**Comment by dasawanaka** [comment]
I honestly don't know which version looks better. I would choose the previous one but let others say.

**Comment by rosolowski** [comment]
> I honestly don't know which version looks better. I would choose the previous one but let others say.

I agree. I brought back margins for now and made the article even smaller.

**Comment by rosolowski** [comment]
Spacing across article is a little smaller, titles instead of subheadings are used and the images are smaller:
image

**Comment by patrycjamia** [comment]
I don't understand why this should be changed, the current version is fine for me. How to use FIBO Viewer is a header, so the larger font introduces readability.

**Review by mereolog — APPROVED** [review]

**Review by dasawanaka — APPROVED** [review]
I understand that if @mereolog has accepted it, then the decision is that it stays as it is.

**Pull request merged**
