### PR TITLE
Standardisation of home page

### LINKED ISSUE #217: Standardisation of home page
We should apply the new style to the landing page, i.e., to https://spec.edmcouncil.org/.

### PR DESCRIPTION
**Pull request by rosolowski**
Closes: #217 

Changes:
- homepage new design
- articles new design
- sligthly changed carousel to look better and have a nicer animation

---

There are articles that are not accessible (not linked anywhere on the page), but they can be accessed by linking directly: /courses , /okgl , /documentation
@mereolog Should these be added to the menu so that users can access them? Currently I left them unlinked, like before.

---

Homepage preview:
image

### CODE REVIEW

**Comment by patrycjamia** [comment]
image
@rr-adam

**Comment by rosolowski** [comment]
> image @rr-adam

@patrycjamia I changed eslint configuration to accept windows style line endings. It should run properly now.

**Review by patrycjamia — APPROVED** [review]

**Comment by mereolog** [comment]
> There are articles that are not accessible (not linked anywhere on the page), but they can be accessed by linking directly: /courses , /okgl , /documentation @mereolog Should these be added to the menu so that users can access them? Currently I left them unlinked, like before.
> 

Yes, leave them as they are now.

**Review by mereolog — APPROVED** [review]
@rr-adam note that docker throws some warnings:

```
WARNING  Compiled with 1 warning5:41:59 AM

 warning  in ./node_modules/bootstrap/dist/css/bootstrap.min.css

Module Warning (from ./node_modules/postcss-loader/dist/cjs.js):
Warning

(6:62003) autoprefixer: Replace color-adjust to print-color-adjust. The color-adjust shorthand is currently deprecated.


  App running at:
  - Local:   http://localhost:8080/idmp/ 

  It seems you are running Vue CLI inside a container.

  Since you are using a non-root publicPath, the hot-reload socket
  will not be able to infer the correct URL to connect. You should
  explicitly specify the URL via devServer.public.

  Access the dev server via http://localhost:<your container's external mapped port>/idmp/
```

**Pull request merged**
