### PR TITLE
Update dependencies across html pages

### LINKED ISSUE #189: Update dependencies across html pages
dependecies should be updated to fix dependabot alerts

### PR DESCRIPTION
**Pull request by rosolowski**
fixes: #189 
Most of the dependecies were updated to latest version in FIBO, AUTO, IDMP and home.

### CODE REVIEW

**Review by mereolog — CHANGES_REQUESTED** [review]
I tried to run this PR in docker (macOS 12.0.1).
After I ran:
`docker-compose --profile=fibo build`
and
`docker-compose --profile fibo up -d`
I got the error:
```
ERROR  Failed to compile with 2 errors8:10:40 AM

 error  in ./src/components/VisNetwork.vue?vue&type=script&lang=js&

Module not found: Error: Can't resolve 'vis-data/peer/esm/vis-data' in '/project/src/components'

 error  in ./node_modules/vis-network/peer/esm/vis-network.js

Module not found: Error: Can't resolve 'vis-data/peer/esm/vis-data.js' in '/project/node_modules/vis-network/peer/esm'

ERROR in ./src/components/VisNetwork.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/VisNetwork.vue?vue&type=script&lang=js&) 114:0-63
Module not found: Error: Can't resolve 'vis-data/peer/esm/vis-data' in '/project/src/components'
 @ ./src/components/VisNetwork.vue?vue&type=script&lang=js& 1:0-216 1:232-235 1:237-450 1:237-450
 @ ./src/components/VisNetwork.vue 2:0-62 3:0-57 3:0-57 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Ontology.vue?vue&type=script&lang=js& 1189:13-1191:33
 @ ./src/views/Ontology.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/views/Ontology.vue 2:0-60 3:0-55 3:0-55 11:2-8
 @ ./src/router.js 123:13-125:29
 @ ./src/main.js 12:0-30 21:10-16 29:10-16

ERROR in ./node_modules/vis-network/peer/esm/vis-network.js 27:0-72
Module not found: Error: Can't resolve 'vis-data/peer/esm/vis-data.js' in '/project/node_modules/vis-network/peer/esm'
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/VisNetwork.vue?vue&type=script&lang=js& 113:0-59 219:24-31
 @ ./src/components/VisNetwork.vue?vue&type=script&lang=js& 1:0-216 1:232-235 1:237-450 1:237-450
 @ ./src/components/VisNetwork.vue 2:0-62 3:0-57 3:0-57 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Ontology.vue?vue&type=script&lang=js& 1189:13-1191:33
 @ ./src/views/Ontology.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/views/Ontology.vue 2:0-60 3:0-55 3:0-55 11:2-8
 @ ./src/router.js 123:13-125:29
 @ ./src/main.js 12:0-30 21:10-16 29:10-16

webpack compiled with 2 errors
(node:28) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by rosolowski** [comment]
> I tried to run this PR in docker (macOS 12.0.1). After I ran: `docker-compose --profile=fibo build` and `docker-compose --profile fibo up -d` I got the error:
> 
> ```
> ...
> ```

@mereolog The problem should be fixed now.

**Review by dasawanaka — CHANGES_REQUESTED** [review]
when i build `home` and run it on docker and go to `localhost:8080` i see this

```
Many more error lines
home_1  |   121:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
home_1  |   122:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
home_1  |   123:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
home_1  |   124:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
home_1  |   125:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
home_1  |
home_1  | ✖ 2275 problems (2275 errors, 0 warnings)
home_1  |   2275 errors and 0 warnings potentially fixable with the `--fix` option.
home_1  |
home_1  | webpack compiled with 1 error
```

**Comment by dasawanaka** [comment]
`fibo`, `auto` and `idmp` pages build but not run

logs is similar so i paste one of them
```
Attaching to html-pages_fibo_1
fibo_1  | yarn run v1.22.17
fibo_1  | $ vue-cli-service serve
fibo_1  |  INFO  Starting development server...
fibo_1  |  ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
fibo_1  |  - configuration.resolve has an unknown property 'fallback'. These properties are valid:
fibo_1  |    object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
fibo_1  |    -> Options for the resolver
fibo_1  | WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
fibo_1  |  - configuration.resolve has an unknown property 'fallback'. These properties are valid:
fibo_1  |    object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
fibo_1  |    -> Options for the resolver
fibo_1  |     at webpack (/project/node_modules/webpack/lib/webpack.js:31:9)
fibo_1  |     at serve (/project/node_modules/@vue/cli-service/lib/commands/serve.js:137:22)
fibo_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
fibo_1  | error Command failed with exit code 1.
fibo_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
html-pages_fibo_1 exited with code 1
```

this error is from `docker`, using `npm run` doesn't have these problems

**Review by patrycjamia — DISMISSED** [review]

**Comment by patrycjamia** [comment]
> `fibo`, `auto` and `idmp` pages build but not run
> 
> logs is similar so i paste one of them
> 
> ```
> Attaching to html-pages_fibo_1
> fibo_1  | yarn run v1.22.17
> fibo_1  | $ vue-cli-service serve
> fibo_1  |  INFO  Starting development server...
> fibo_1  |  ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> fibo_1  |  - configuration.resolve has an unknown property 'fallback'. These properties are valid:
> fibo_1  |    object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
> fibo_1  |    -> Options for the resolver
> fibo_1  | WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
> fibo_1  |  - configuration.resolve has an unknown property 'fallback'. These properties are valid:
> fibo_1  |    object { alias?, aliasFields?, cachePredicate?, cacheWithContext?, concord?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
> fibo_1  |    -> Options for the resolver
> fibo_1  |     at webpack (/project/node_modules/webpack/lib/webpack.js:31:9)
> fibo_1  |     at serve (/project/node_modules/@vue/cli-service/lib/commands/serve.js:137:22)
> fibo_1  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
> fibo_1  | error Command failed with exit code 1.
> fibo_1  | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> html-pages_fibo_1 exited with code 1
> ```
> 
> this error is from `docker`, using `npm run` doesn't have these problems

It works correctly for me.

**Comment by patrycjamia** [comment]
> when i build `home` and run it on docker and go to `localhost:8080` i see this
> 
> ```
> Many more error lines
> home_1  |   121:3   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> home_1  |   122:10  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> home_1  |   123:1   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> home_1  |   124:27  error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> home_1  |   125:9   error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style
> home_1  |
> home_1  | ✖ 2275 problems (2275 errors, 0 warnings)
> home_1  |   2275 errors and 0 warnings potentially fixable with the `--fix` option.
> home_1  |
> home_1  | webpack compiled with 1 error
> ```

 on 'home' I get the same error as @dasawanaka. 'Fibo' run corectlly.

**Review by mereolog — CHANGES_REQUESTED** [review]
@rr-adam please resolve the merge conflicts.

**Comment by rosolowski** [comment]
@patrycjamia @dasawanaka if I understand correctly the `error  Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style` error appears because the '@vue/airbnb' eslint extension expects all files in home to use LF line endings. I think we should keep the extension there, or even add it to fibo, idmp and auto as well.

To get rid of the problem when developing on windows we can do one of these:

1. Change git config with `git config --global core.autocrlf false`, which will stop git from converting line endings to CRLF on windows. - make sure you set up the editor to use LF line endings too.
2. I could add eslint rule to ignore line endings type completely both on windows and unix.


The https://github.com/edmcouncil/html-pages/pull/190#issuecomment-1123318526 problem, I'm not sure why it appears.

**Review by mereolog — APPROVED** [review]
For idmp I got this warning:
```
(node:29) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 upgrade listeners added to [Server]. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Review by dasawanaka — APPROVED** [review]
Jenkins doesn't report any errors, so it's running fine

**Pull request merged**
