### PR TITLE
159 IDMP pages

### LINKED ISSUE #159: IDMP pages
IDMP pages

### PR DESCRIPTION
**Pull request by dasawanaka**
IDMP pages

Fixed: #159 

- [x]  created environment for work (copy of fibo folder and adding idmp to docker composer) @dasawanaka 
- [x]  update menu @rr-adam 
- [x]  slider content @rr-adam 
- [x]  change footer.vue and home.vue content @dasawanaka 
- [x]  updating the product page and all sub pages (under construction)
- [x]  leave ontology versioning or remove it(with fragment in `how to use`)? 
- [x]  leave new issue button(and update link) or remove it? 
- [x]  `how to use viewer` leave maturity level description?

### CODE REVIEW

**Comment by rosolowski** [comment]
Menu content and slides are now updated. Unused pages from FIBO got deleted.

image

**Comment by dasawanaka** [comment]
> * [ ] updating the product page and all sub pages
> * [ ]   leave ontology versioning or remove it(with fragment in `how to use`)?
> * [ ]   leave new issue button(and update link) or remove it?
> * [ ]   `how to use viewer` leave maturity level description?

@mereolog, requires additional information about product page content and others.

**Review by mereolog — CHANGES_REQUESTED** [review]
It does not seem to be running from within docker.
@dasawanaka, could you "dockerise" it?

**Comment by dasawanaka** [comment]
> It does not seem to be running from within docker.
> @dasawanaka, could you "dockerise" it?

I added a jenkins profile for idmp but I haven't updated the readme file yet. 
run `docker-compose --profile=idmp build` and next `docker-compose --profile idmp up -d`
Similar as for other profiles

**Comment by mereolog** [comment]
> > It does not seem to be running from within docker.
> > @dasawanaka, could you "dockerise" it?
> 
> I added a jenkins profile for idmp but I haven't updated the readme file yet. run `docker-compose --profile=idmp build` and next `docker-compose --profile idmp up -d` Similar as for other profiles

Call to http://localhost:8080/idmp gives me this error:
```
Failed to compile.

./src/main.js
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
TypeError: eslint.CLIEngine is not a constructor
    at Object.module.exports (/project/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:223:27)
```

**Comment by dasawanaka** [comment]
> Call to http://localhost:8080/idmp gives me this error:
> 
> ```
> Failed to compile.
> 
> ./src/main.js
> Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> TypeError: eslint.CLIEngine is not a constructor
>     at Object.module.exports (/project/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:223:27)
> ```

Try now, i downgraded some dependencies based on issue with similar problem(that could resolve problem), but I don't have this problem. I tried deleting the cache, and installing the modules again, but didn't get the problem.

**Comment by rosolowski** [comment]
There is some unused code left from FIBO:

- src/store/OWL.js - unused script

There are also pages that should be potentially deleted:

- Schema.vue
- Contact.vue (not linked anywhere)

@mereolog should the pages above be deleted?

**Comment by mereolog** [comment]
> There is some unused code left from FIBO:
> 
> * src/store/OWL.js - unused script
> 
> There are also pages that should be potentially deleted:
> 
> * Schema.vue
> * Contact.vue (not linked anywhere)
> 
> @mereolog should the pages above be deleted?

If they are not linked, they should be deleted.

**Comment by mereolog** [comment]
> > Call to http://localhost:8080/idmp gives me this error:
> > ```
> > Failed to compile.
> > 
> > ./src/main.js
> > Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):
> > TypeError: eslint.CLIEngine is not a constructor
> >     at Object.module.exports (/project/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:223:27)
> > ```
> 
> Try now, i downgraded some dependencies based on issue with similar problem(that could resolve problem), but I don't have this problem. I tried deleting the cache, and installing the modules again, but didn't get the problem.

Now I got this:
```
Failed to compile.

./src/main.js
Module build failed (from ./node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js):

Error: .eslintrc.js:
	Configuration for rule "properties" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '"never"').

    at validateRuleOptions (/project/node_modules/eslint/lib/shared/config-validator.js:138:19)
    at /project/node_modules/eslint/lib/shared/config-validator.js:193:9
    at Array.forEach (<anonymous>)
    at validateRules (/project/node_modules/eslint/lib/shared/config-validator.js:190:30)
    at validateConfigArray (/project/node_modules/eslint/lib/shared/config-validator.js:337:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/project/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at CLIEngine.isPathIgnored (/project/node_modules/eslint/lib/cli-engine/cli-engine.js:951:18)
    at CLIEngine.executeOnText (/project/node_modules/eslint/lib/cli-engine/cli-engine.js:868:38)
    at lint (/project/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:278:17)
    at transform (/project/node_modules/@vue/cli-plugin-eslint/node_modules/eslint-loader/index.js:252:18)
    at /project/node_modules/loader-fs-cache/index.js:127:18
    at ReadFileContext.callback (/project/node_modules/loader-fs-cache/index.js:31:14)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:261:13)
```

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka could you resolve the merge conflict(s), please?

**Comment by rosolowski** [comment]
I made the following changes to the IDMP frontend:

- add search box optimization the same as fibo and auto ( #163 )
- use entity endpoint as mentioned in https://github.com/edmcouncil/html-pages/pull/169

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka please resolve the merge conflict in fibo/src/views/Ontology.vue.

**Review by mereolog — CHANGES_REQUESTED** [review]
When I trie to run the last commit in docker, I got this error:
```
ERROR  Failed to compile with 1 error12:17:03 PM

Syntax Error: Error: .eslintrc.js:
	Configuration for rule "ignoreDestructuring" is invalid:
	Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed 'true').
    at Array.forEach (<anonymous>)
```

**Comment by patrycjamia** [comment]
The site is running but there is no access to OV.

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka in the header banner instead of
EXECUTIVE SUMMARY
IDMP COMMON CORE ONTOLOGY
put
IDMP COMMON CORE ONTOLOGY
IDEA

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
