### PR TITLE
Sparse display of owl restrictions - frontend

### LINKED ISSUE #375: Sparse display of owl restrictions - frontend
The app should show if a restriction can be inferred from another restriction.
Backend implementation and example: https://github.com/edmcouncil/onto-viewer/pull/353

### PR DESCRIPTION
**Pull request by rosolowski**
closes: #375 

Inferable restrictions have `Black 60%` color and a tooltip that explains the convention.

image

### CODE REVIEW

**Review by mereolog — COMMENTED** [review]
This is how it looks on a Dell screen for Safari macOS:
image
Frankly, I cannot see the difference between inferable and the rest.

**Comment by rosolowski** [comment]
The difference should now be more noticeable

**Comment by mereolog** [comment]
> The difference should now be more noticeable

Looks better now.

**Comment by mereolog** [comment]
@rr-adam could you change 'This restriction is inferable' to 'This restriction is inferable from other restrictions.'?

**Comment by rosolowski** [comment]
@mereolog The tooltip has been updated

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
