### PR TITLE
New GUI for AUTO

### LINKED ISSUE #142: New GUI for Auto
We need to update auto pages to the new GUI design

### PR DESCRIPTION
**Pull request by dasawanaka**
Signed-off-by: dasawanaka <michal.19.daniel.96@gmail.com>

Fixes: #142 

In header we can use one of two versions:
A:
image
B:
image

What version of the header should use?

### CODE REVIEW

**Comment by patrycjamia** [comment]
The checkboxes should be black.
image

**Comment by patrycjamia** [comment]
Maturity level is not displayed correctly.
image

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comments are above.

**Comment by patrycjamia** [comment]
> Signed-off-by: dasawanaka [michal.19.daniel.96@gmail.com](mailto:michal.19.daniel.96@gmail.com)
> 
> Issue: #142
> 
> In header we can use one of two versions: A: image B: image
> 
> What version of the header should use?

In my opinion, B.

**Comment by mereolog** [comment]
> > Signed-off-by: dasawanaka [michal.19.daniel.96@gmail.com](mailto:michal.19.daniel.96@gmail.com)
> > Issue: #142
> > In header we can use one of two versions: A: image B: image
> > What version of the header should use?
> 
> In my opinion, B.

I agree with @patrycjamia.

**Comment by patrycjamia** [comment]
You should also remember to update the configuration files. e.g. dataType is displayed in other section.

**Comment by dasawanaka** [comment]
> Maturity level is not displayed correctly. image

[Issue: 184](https://github.com/edmcouncil/onto-viewer/issues/184)

**Comment by patrycjamia** [comment]
@mereolog 
It's probably for another task. Displaying 'created' in the other section. https://spec.edmcouncil.org/auto/ontology/VS/VehicleSignals/

image
image

**Comment by patrycjamia** [comment]
@dasawanaka Tree-view do not display of a resource's parents.

**Comment by mereolog** [comment]
> @mereolog It's probably for another task. Displaying 'created' in the other section. https://spec.edmcouncil.org/auto/ontology/VS/VehicleSignals/
> 
> image image

1. Does 'other' mean that the config files need to be updated? If so, @przemekgradzki could you do it?
2. I presume that created attribute corresponds to the piece below. Then it may be displayed in Meta-information section.

```
<owl:Ontology rdf:about="https://spec.edmcouncil.org/auto/ontology/VS/VehicleSignals/">
[...]
<dct:created rdf:datatype="&xsd;dateTime">2018-01-10T00:00:00</dct:created>
```

**Comment by dasawanaka** [comment]
> 1. Does 'other' mean that the config files need to be updated? If so, `@przemekgradzki `could you do it?

Yes, but the `value` is not displayed

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka could you resolve merge conflict(s), please?

**Comment by rosolowski** [comment]
I made the following changes to the new AUTO gui:

- use [find search](https://github.com/edmcouncil/onto-viewer/blob/develop/api-doc/rest_api.md#apifind-get) api
- use entity endpoint as mentioned in https://github.com/edmcouncil/html-pages/pull/169

**Comment by dasawanaka** [comment]
Remember to update the prod viewer as mentioned in the [comment](https://github.com/edmcouncil/html-pages/pull/169#issuecomment-1081717754)

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka could you remove the merge conflict?

**Comment by dasawanaka** [comment]
Jenkins on publishing stage has [error](https://jenkins.edmcouncil.org/blue/organizations/jenkins/auto-html-pages/detail/PR-157/8/pipeline): 

```
Unstashing the output of the publish stage
Failed to extract htmlpages.tar.gzFailed the "Publish" stage: java.io.IOException: Failed to extract htmlpages.tar.gz
```

I don't know if it should be like this

**Review by mereolog — CHANGES_REQUESTED** [review]
We need to implement the path/tree selector.
image
image

**Comment by patrycjamia** [comment]
The font should be smaller, as in fibo.
image

**Comment by dasawanaka** [comment]
@patrycjamia i can't rerequest to review, please check changes now :D

**Review by mereolog — CHANGES_REQUESTED** [review]
Could we have the instrumentation as well - see: https://github.com/edmcouncil/html-pages/pull/177?

**Comment by rosolowski** [comment]
In https://github.com/edmcouncil/html-pages/pull/157/commits/352ff54b79cc788d9f366ac4954c9a1c682d6bd2 the following changes were added to AUTO frontend:

- https://github.com/edmcouncil/html-pages/pull/199
- https://github.com/edmcouncil/html-pages/pull/192

**Comment by mereolog** [comment]
@dasawanaka please resolve the merge conflict.

**Review by mereolog — CHANGES_REQUESTED** [review]
When I tried to run this in docker, I got this error:
```
yarn run v1.22.19
$ vue-cli-service serve
 INFO  Starting development server...
 ERROR  Failed to compile with 1 error10:03:26 AM

 error  in ./node_modules/linkify-html/dist/linkify-html.module.js

Module not found: Error: Can't resolve 'linkifyjs' in '/project/node_modules/linkify-html/dist'

ERROR in ./node_modules/linkify-html/dist/linkify-html.module.js 1:0-37
Module not found: Error: Can't resolve 'linkifyjs' in '/project/node_modules/linkify-html/dist'
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/chunks/STRING.vue?vue&type=script&lang=js& 42:0-39 58:25-36
 @ ./src/components/chunks/STRING.vue?vue&type=script&lang=js& 1:0-218 1:234-237 1:239-454 1:239-454
 @ ./src/components/chunks/STRING.vue 2:0-58 3:0-53 3:0-53 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/Ontology/PropertiesList.vue?vue&type=script&lang=js& 77:13-79:25
 @ ./src/components/Ontology/PropertiesList.vue?vue&type=script&lang=js& 1:0-226 1:242-245 1:247-470 1:247-470
 @ ./src/components/Ontology/PropertiesList.vue 2:0-66 3:0-61 3:0-61 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/Ontology/ResourceSection.vue?vue&type=script&lang=js& 27:0-46 30:20-34
 @ ./src/components/Ontology/ResourceSection.vue?vue&type=script&lang=js& 1:0-227 1:243-246 1:248-472 1:248-472
 @ ./src/components/Ontology/ResourceSection.vue 2:0-67 3:0-62 3:0-62 9:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Ontology.vue?vue&type=script&lang=js& 820:13-822:47
 @ ./src/views/Ontology.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/views/Ontology.vue 2:0-60 3:0-55 3:0-55 11:2-8
 @ ./src/router.js 59:13-61:29
 @ ./src/main.js 11:0-30 30:10-16

webpack compiled with 1 error
```
auto image was rebuilt beforehand.

**Review by mereolog — CHANGES_REQUESTED** [review]
```
INFO  Starting development server...
 ERROR  Failed to compile with 1 error7:35:47 AM

 error  in ./node_modules/linkify-html/dist/linkify-html.module.js

Module not found: Error: Can't resolve 'linkifyjs' in '/project/node_modules/linkify-html/dist'

ERROR in ./node_modules/linkify-html/dist/linkify-html.module.js 1:0-37
Module not found: Error: Can't resolve 'linkifyjs' in '/project/node_modules/linkify-html/dist'
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/chunks/STRING.vue?vue&type=script&lang=js& 42:0-39 58:25-36
 @ ./src/components/chunks/STRING.vue?vue&type=script&lang=js& 1:0-218 1:234-237 1:239-454 1:239-454
 @ ./src/components/chunks/STRING.vue 2:0-58 3:0-53 3:0-53 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/Ontology/PropertiesList.vue?vue&type=script&lang=js& 77:13-79:25
 @ ./src/components/Ontology/PropertiesList.vue?vue&type=script&lang=js& 1:0-226 1:242-245 1:247-470 1:247-470
 @ ./src/components/Ontology/PropertiesList.vue 2:0-66 3:0-61 3:0-61 10:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/components/Ontology/ResourceSection.vue?vue&type=script&lang=js& 27:0-46 30:20-34
 @ ./src/components/Ontology/ResourceSection.vue?vue&type=script&lang=js& 1:0-227 1:243-246 1:248-472 1:248-472
 @ ./src/components/Ontology/ResourceSection.vue 2:0-67 3:0-62 3:0-62 9:2-8
 @ ./node_modules/babel-loader/lib/index.js??clonedRuleSet-40[0].rules[0].use[0]!./node_modules/@vue/vue-loader-v15/lib/index.js??vue-loader-options!./src/views/Ontology.vue?vue&type=script&lang=js& 820:13-822:47
 @ ./src/views/Ontology.vue?vue&type=script&lang=js& 1:0-214 1:230-233 1:235-446 1:235-446
 @ ./src/views/Ontology.vue 2:0-60 3:0-55 3:0-55 11:2-8
 @ ./src/router.js 59:13-61:29
 @ ./src/main.js 11:0-30 30:10-16

webpack compiled with 1 error

```

**Review by mereolog — CHANGES_REQUESTED** [review]
The statistics section is empty:
image

**Review by mereolog — APPROVED** [review]
@rr-adam I am assuming that updates for products pages will be done in https://github.com/edmcouncil/html-pages/pull/157.

**Comment by patrycjamia** [comment]
@rr-adam For fibo, the icons and font are smaller than for idmp and auto.
image

**Comment by rosolowski** [comment]
> @rr-adam I am assuming that updates for products pages will be done in https://github.com/edmcouncil/html-pages/pull/157.
> @rr-adam For fibo, the icons and font are smaller than for idmp and auto. 

@patrycjamia @mereolog  Yes, I will change FIBO, IDMP and AUTO tutorial to use global article style added in #197 , so the change will be done in #197 when this PR is merged, if that's ok.

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
