### PR TITLE
New gui design

### PR DESCRIPTION
**Pull request by dasawanaka**
Pull Request includes all changes from #108 and additional ones from my branch. I made the main page elements such as top menu, module tree view, footer and main page fibo/ontology.

### CODE REVIEW

**Comment by mereolog** [comment]
'Private Limited Companies Ontology' is displayed in a confusing way:
image
At first I thought that something was missing and but after a while I realized that the "first" empty line is the beginning of the 'Private Limited Companies Ontology' display.

We should avoid displaying items in this list with such long blanks - probably the best way out is to squeeze these items so that each item can be displayed in one line. Alternatively we can display some of them in two lines - but without such "leading" blank space as it is now.

Btw., the old gui has this right:
image

I am testing this PR using Safari 15.1 and Chrome 96.0.4664.110 on macOs 12.1 (display resolution is 3072 × 1920).

**Comment by mereolog** [comment]
Similar issue here:
image

**Comment by mereolog** [comment]
In my view the space between "registration identitifier" and "Show more" is too wide:
image
But other reviewers may be of different opinion.

**Comment by mereolog** [comment]
'Is about' should start with the lower-case 'i':
image

**Comment by mereolog** [comment]
Display for EntityLegalFormScheme has an extra section 'other':
image
This section is absent in the current gui:
image

**Comment by mereolog** [comment]
Looking at how CapLoan is displayed one can notice that two phrases are used "to show more":
1. see more
2. show more
image
Use only "Show more" (and, respectively, Show less).

**Comment by mereolog** [comment]
When the domain/module/ontology tree expands (at a certain level) the triangle that indicates the contents of an item should be rotated (clockwise).
image
Compare this to:
image

**Comment by mereolog** [comment]
The copyright date at the bottom should be updated to 2022.
image

**Comment by mereolog** [comment]
I think the the font size for paths should be the same size as the font for label, definition, etc:
image
But other reviewers may be of different opinion.
(I am aware that the smaller font follows the design's mockup.)

**Comment by mereolog** [comment]
FIBO VIEWER > FIBO Viewer
image

**Comment by mereolog** [comment]
Pages linked to the FIBO Viewer should follow the same font type, color and size pattern.
Currently pages like https://spec.edmcouncil.org/fibo/ do not meet the requirement.

**Review by mereolog — CHANGES_REQUESTED** [review]
My detailed comments are above.

**Comment by patrycjamia** [comment]
http://localhost:8080/fibo/ontology/FND/MetadataFND/FNDDomain
The layout of the elements is very dispersed and looks strange.
image

**Comment by patrycjamia** [comment]
Wouldn't it be better to make the font smaller so that 'the' doesn't show up by itself on the line?
image

**Comment by patrycjamia** [comment]
The colour of the nodes does not seem to have been changed.
image

**Comment by patrycjamia** [comment]
If there is no description in the search results, isn't it better to reduce this empty space? It would look more aesthetically pleasing.
image

**Comment by patrycjamia** [comment]
Should the text 'search fibo' be displayed?
image

**Comment by patrycjamia** [comment]
The 'x', which clears the field of text, overlaps the search phrase.
image

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comments are above.

**Pull request merged**
