### PR TITLE
Tree-view display of a resource's parents

### PR DESCRIPTION
**Pull request by rosolowski**
Issue: https://github.com/edmcouncil/html-pages/issues/149
User can now toggle paths display between tree and breadcrumb view.

image

### CODE REVIEW

**Comment by dasawanaka** [comment]
Can it have some lines? it look similar as module tree on left but is more complicated and looking on it is not clear what is parent of others. In protege tree view has lines and it look clearly. 
image

**Comment by mereolog** [comment]
> Can it have some lines? it look similar as module tree on left but is more complicated and looking on it is not clear what is parent of others. In protege tree view has lines and it look clearly.
> image

I do not like the lines.
@patrycjamia, @trojczak, @przemekgradzki  could we have a vote about this?

**Comment by trojczak** [comment]
On the picture presented by @rr-adam it looks clear enough for me without lines. But I would like to see more complicated cases of inheritance to make sure.

**Comment by rosolowski** [comment]
Large tree example:

image

**Comment by trojczak** [comment]
Taking this example into consideration I would go for adding lines if it is not much work.

**Comment by mereolog** [comment]
Could we have the focus class, e.g., mortgage, highlighted in some way, e.g., by bold face, color, etc.?

**Comment by rosolowski** [comment]
> Could we have the focus class, e.g., mortgage, highlighted in some way, e.g., by bold face, color, etc.?

Yes, I will add this and the lines.

**Comment by rosolowski** [comment]
Added lines and selected class highlight:

image

**Review by dasawanaka — CHANGES_REQUESTED** [review]
Seems to be working fine, but..

- **To resolve:** when you refresh the page, the tree view selection disappears and you have to select it again. If someone preferred the tree view, it was better to save this choice.
- **For discussion:** Regarding the large tree view, I wonder if it can be collapsed somehow.

**Review by mereolog — CHANGES_REQUESTED** [review]
Looks pretty good, but can we have the toggle button with two labels, e.g., 'Paths' and 'Tree'.

**Review by patrycjamia — DISMISSED** [review]

**Review by mereolog — CHANGES_REQUESTED** [review]
@rr-adam apologies for being picky, but could you make the toggle (bar) twice as long?
@dasawanaka, @trojczak, @patrycjamia what do you think?

**Comment by trojczak** [comment]
IMO it's OK in the current form, but if the toggle button will be a bit bigger, it won't do any harm.

**Comment by rosolowski** [comment]
Made the toggle bigger:

image

**Review by mereolog — APPROVED** [review]

**Review by dasawanaka — APPROVED** [review]

**Pull request merged**
