### PR TITLE
Fix problem with downloading files in wrong location

### LINKED ISSUE #248: Problem with displaying status jpg files
Downloaded files from strapi does't display

### PR DESCRIPTION
**Pull request by dasawanaka**
Resolve: #248 

Signed-off-by: Michał Daniel <michal.daniel@makolab.com>

### CODE REVIEW

**Review by mereolog — DISMISSED** [review]
I only test the required functionalities.

**Review by rosolowski — CHANGES_REQUESTED** [review]
Images in home page work fine, but in articles they are fetched directly from strapi,
example of problem from FIB-DM article:
image
example of working as intended in home:
image

**Review by przemekgradzki — APPROVED** [review]

**Review by przemekgradzki — CHANGES_REQUESTED** [review]
Confirm comment https://github.com/edmcouncil/html-pages/pull/249#pullrequestreview-1110829795 - images in [FIBO-DM](http://fibo-viewer.korora.makolab.net/fibo/page/data-model) are downloaded from STRAPI URL

**Review by mereolog — CHANGES_REQUESTED** [review]
When I try to open .../fibo/page/data-model in the test environment, I get the 'Connection Failed' error - I tested this in Safari and Chrome for MacOS.

image

**Review by mereolog — APPROVED** [review]
I just checked the display functionality.

**Review by rosolowski — APPROVED** [review]

**Pull request merged**
