### PR TITLE
Ontology update log event visible to onto-viewer users

### LINKED ISSUE #172: Ontology update log event visible to onto-viewer users - frontend
User should have access to information about viewer:

- stats ([documentation](https://github.com/edmcouncil/onto-viewer/blob/develop/api-doc/rest_api.md#7-simple-stats))
- missing imports ([documentation](https://github.com/edmcouncil/onto-viewer/blob/develop/api-doc/rest_api.md#11-missing-imports))

### PR DESCRIPTION
**Pull request by rosolowski**
Fixes: https://github.com/edmcouncil/html-pages/issues/172
Added Stats component and placed it in the left column, below fibo modules. 
In the left image there are no missing imports, in the right image there are 2 example missing imports:

image

### CODE REVIEW

**Comment by dasawanaka** [comment]
I don't know if it makes sense to display the reason for missing imports, this is java stack trace errors, no need to be visible, maybe with an extension option.

This red hurts my eyes so much, but i dont know we can do something with this

**Comment by trojczak** [comment]
I agree with @dasawanaka, these colours should not be so aggressive. Also, there shouldn't be exceptions displayed.

**Comment by rosolowski** [comment]
@dasawanaka @trojczak Let me know if it's better now:

image

**Comment by trojczak** [comment]
@rr-adam IMO still too bright and hard to read. Try something like backgrounds of "danger" or "warning" here: https://getbootstrap.com/docs/4.0/components/alerts/

**Comment by rosolowski** [comment]
Ok, I changed it to be lighter, similar to bootstrap:

image

**Comment by dasawanaka** [comment]
> Ok, I changed it to be lighter, similar to bootstrap:
> 
> image

Looks ok, but why can't it have color like these sections? 

image

The whole page is kept in a dark style, this color here does not look good.  Maybe let @patrycjamia  speak about the color :)

**Comment by patrycjamia** [comment]
> > Ok, I changed it to be lighter, similar to bootstrap:
> > image
> 
> Looks ok, but why can't it have color like these sections?
> 
> image
> 
> The whole page is kept in a dark style, this color here does not look good. Maybe let @patrycjamia speak about the color :)

In my opinion, 'missing imports' does not need to have a red background. The page looks inconsistent. The header 'missing imports' is enough information.

**Comment by rosolowski** [comment]
Changed the background to the default gray:

image

**Comment by patrycjamia** [comment]
> Changed the background to the default gray:
> 
> image

For me it looks better.

**Review by patrycjamia — DISMISSED** [review]

**Comment by dasawanaka** [comment]
i will aprove when conflict was resolved

**Review by mereolog — CHANGES_REQUESTED** [review]
@rr-adam could you resolve the merge conflict?

**Comment by rosolowski** [comment]
@dasawanaka @mereolog conflicts are resolved

**Review by mereolog — CHANGES_REQUESTED** [review]
Change:
FIBO Informations
to
FIBO Instrumentation

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Review by dasawanaka — APPROVED** [review]

**Pull request merged**
