### PR TITLE
178 prototype pollution in minimist

### LINKED ISSUE #178: Dependabot alerts - Prototype Pollution in minimist
We do not have 'minimist' directly in the dependencies.
Should update the following packages that contain it:

- [ ] @vue/cli-service
- [ ] @vue/cli-plugin-eslint 
- [ ] @vue/eslint-config-airbnb

Is likely to return a problem with  [issuecomment-1046656161](https://github.com/edmcouncil/html-pages/pull/132#issuecomment-1046656161), backport to an older version fixes this problem, When dependencies are updated, cooperation with @mereolog will be required to check for compatibility in IOS system with docker.

### PR DESCRIPTION
**Pull request by dasawanaka**
Fixes: #178 

Update dependencies in 

- [x] fibo
- [x] auto
- [x] idmp

**Please check carefully that everything works and starts correctly**

### CODE REVIEW

**Comment by dasawanaka** [comment]
[same error as in](https://github.com/edmcouncil/html-pages/pull/157#issuecomment-1097171131) `#157` 

```
continuous-integration/jenkins/pr-merge — This commit cannot be built 
> Failed to extract htmlpages.tar.gz
```

**Comment by przemekgradzki** [comment]
> [same error as in](https://github.com/edmcouncil/html-pages/pull/157#issuecomment-1097171131) `#157`
> 
> ```
> continuous-integration/jenkins/pr-merge — This commit cannot be built 
> > Failed to extract htmlpages.tar.gz
> ```

[auto/package-lock.json](https://github.com/edmcouncil/html-pages/blob/178-prototype-pollution-in-minimist/auto/package-lock.json) should be undeleted - see [jenkins htmlpages.log](https://jenkins.edmcouncil.org/view/html-pages/job/auto-html-pages/view/change-requests/job/PR-181/lastFailedBuild/artifact/htmlpages.log)

> npm ERR! The `npm ci` command can only install with an existing package-lock.json or
> npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
> npm ERR! later to generate a package-lock.json file, then try again.

**Review by przemekgradzki — CHANGES_REQUESTED** [review]
See [comment](https://github.com/edmcouncil/html-pages/pull/181/#issuecomment-1097468012)

**Review by mereolog — APPROVED** [review]

**Comment by patrycjamia** [comment]
image
For idmp  and auto the config is probably not up to date.

**Review by patrycjamia — APPROVED** [review]

**Review by przemekgradzki — APPROVED** [review]

**Pull request merged**
