### PR TITLE
Displays flag icons instead of language tags

### LINKED ISSUE #104: Displays flag icons instead of language tags
Displays flag icons instead of language tags, e.g., @en 

examples: [Poland](https://www.omg.org/spec/LCC/Countries/ISO3166-1-CountryCodes/Poland), [jurisdiction of Poland](https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/EasternEuropeGovernmentEntitiesAndJurisdictions/JurisdictionOfPoland), [Car control ontology (CC)](https://spec.edmcouncil.org/auto/ontology/DE/CarControl/)

### PR DESCRIPTION
**Pull request by dasawanaka**
To display language flags, I used the vue-lang-code-flags package under the MIT license. Changes were implemented for fibo and auto pages. 

If pr should be to another branch please let me know and I will correct it

Issue: #104 

Signed-off-by: dasawanaka <michal.19.daniel.96@gmail.com>

### CODE REVIEW

**Review by mereolog — CHANGES_REQUESTED** [review]
I deployed the PR in docker (docker-compose --profile fibo up -d) and got this error when I navigated to http://localhost:8080/fibo:
```
Failed to compile.

./src/main.js
Module not found: Error: Can't resolve 'vue-lang-code-flags' in '/project/src'
```
The docker log file has this:
```
fibo_1  |  ERROR  Failed to compile with 1 errors4:24:29 PM

fibo_1  | 

fibo_1  | This dependency was not found:

fibo_1  | 

fibo_1  | * vue-lang-code-flags in ./src/main.js

fibo_1  | 

fibo_1  | To install it, you can run: npm install --save vue-lang-code-flags
```

**Comment by dasawanaka** [comment]
Everything works fine for me, I don't get any errors on startup or when browsing. 
I used docker on a clean cloned repository. I used like you the command `docker-compose --profile fibo up -d`, but did not encounter any problems.

**Comment by mereolog** [comment]
I ran it on macOS 12.0.1.
@przemekgradzki, @trojczak could you test it in your environments?

**Comment by trojczak** [comment]
I have the same error message as @mereolog. I run it with `docker-compose up -d` from `onto-viewer` which uses [this Dockerfile](https://github.com/edmcouncil/html-pages/blob/develop/Dockerfile).

**Comment by mereolog** [comment]
https://github.com/edmcouncil/html-pages/pull/105#pullrequestreview-801523154 can be ignored now - one needs to build docker image beforehand.

**Pull request closed without merging**
