### PR TITLE
Strapi based auth feature

### LINKED ISSUE #476: Strapi based auth feature
Add strapi based auth feature

### PR DESCRIPTION
**Pull request by rosolowski**
closes: #476 

Work in progress

---

- [x] Initial implementation
- [x] Improved password recovery process
- [x] Toast notifications after login/register/recovery/login expiration
- [x] Validate register inputs on frontend to prevent sending unnecessary requests
- [x] Email validation in register process
- [x] Mobile styles
- [x] Password strength check

---

New variable can be added to Config -> variables: `authEnabled`. When set to `true`, the login/register will be enabled on frontend.

image

When frontend is built with this variable set to `true`, in the ontology viewer website header there will be "Login" option that opens auth modal.

### CODE REVIEW

**Review by mereolog — CHANGES_REQUESTED** [review]
@rr-adam can we have the login name next to the Menu sandwich and not in the middle, i.e., can we have it at the position where the login button is?

image

image

**Comment by mereolog** [comment]
Perhaps displaying a human name instead of their email will be more humane?

image

**Comment by przemekgradzki** [comment]
Link to reset password should be sent as link, not as plain text:
image

the above message also lacks information about the account name/email.

**Comment by przemekgradzki** [comment]
There is no information about the account name/email in the _Reset password_ window.
image

If the user wants to save the credentials in a password manager (e.g. [KeePassXC](https://keepassxc.org/)), the account name/email will not be saved there.

**Comment by przemekgradzki** [comment]
I created a user called _**Login**_ and based on the screenshot below:
image
I don't know if I'm logged in or not

---

Just clicking on the username:
image

shows that I am logged in. However, this can be misleading.

**Review by przemekgradzki — CHANGES_REQUESTED** [review]
See comments

**Comment by rosolowski** [comment]
Added a user icon next to the username when user is logged in:
image

With this the user can tell whether he is logged in or not easier.

During password reset there is now e-mail field, it's automatically filled - the e-mail value is passed through a query parameter in password recovery link in email. The field is greyed out and cannot be edited:
image

**Review by przemekgradzki — APPROVED** [review]

**Review by mereolog — APPROVED** [review]

**Pull request merged**
