### PR TITLE
General webpage to work with strapi

### LINKED ISSUE #171: Move site content to Headless CMS + Auth server
Currently the site content is stored in vue files, to change it you need to create a pr, wait for reviews and only then the updated content is available. This increases the time it takes to implement content and changes and adds an extra step by involving additional people. 

My suggestion would be to use headless cms and keep all the site content out of the templates. 

A headless content management system, or headless CMS, is a back-end-only content management system. Such systems include their own dashboard, login and users, content can be added on your own defined templates and will be made available by endpoint or in the case of some headless cms, you can perform graphql queries. 

On 'html-pages' side there would be only downloading data from api and displaying them. As headless cms do not have a front end, connecting them to our solutions in html pages will be easier as it will not interfere with the part of application which will download and display data from onto-viewer. Having separate front-end and back-end is also a standard that would be kept here.

The front-end would need a proper reformatting of the results, the menu could also be moved along with the possibility to manipulate the content using it. 

What kind of content should be available to change from the cms should be discussed separately. Based on my limited experience with STRAPI([page](https://strapi.io), [demo](https://strapi.io/demo)), I can say that there would be no need to create this cms for each site separately and it would be possible to manage them all from one panel by creating appropriate content types for each site. 

The [Strapi](https://strapi.io/features) I mentioned earlier:

-  is open source, 
- we can make custom plugins, 
- we can use rest and graphQL, 
- it's writen in javascript, 
- supported db: SQLite, MongoDB, MySQL, Postgres, 
- have authentication & permissions system
 
Alternatives: 

- [Sanity](https://www.sanity.io/docs/getting-started)
- [Contentful](https://www.contentful.com/features/)
- [other](https://www.g2.com/categories/headless-cms/free)

### PR DESCRIPTION
**Pull request by dasawanaka**
Closes #171 

Work:
- dynamic content from strapi as a backend
- mapping: index.vue, /ontology
    -   _/page/_page_ (removed)
- elements in strapi: 
    -  menu dropdown
    - copyright
    - home content
    - /page/_page - content builded from separate elements on strapi dashboard

TODO: 

- [x] https://github.com/edmcouncil/html-pages/pull/236
- [x] `Report a problem` button 
- [x] doubled home page (one generate on backend, second on frontend)
- [x] broken routers operations on /ontology page
- [x] style on all pages (ex. /ontology), some rules are broken or not work in current version
- [x] new collection for articles insted of silnge type page in strapi
- [x] Error handling ex: 
```
[Vue warn]: Error in data(): "TypeError: Cannot read properties of undefined (reading 'length')"                                                09:51:13

found in

---> <SlideCarousel> at components/SlideCarousel.vue
       <HeaderComponent> at components/HeaderComponent.vue
         <PageView> at pages/index.vue
           <Nuxt>
             <Layouts/default.vue> at layouts/default.vue
               <Root>
```
- [x] page title
- [x] https://github.com/edmcouncil/html-pages/pull/231
- [x] https://github.com/edmcouncil/html-pages/pull/227
- [x] https://github.com/edmcouncil/html-pages/pull/225
- [x] https://github.com/edmcouncil/html-pages/pull/223
- [x] https://github.com/edmcouncil/html-pages/pull/216
- [x] https://github.com/edmcouncil/html-pages/pull/214
- [x] https://github.com/edmcouncil/html-pages/pull/212

For new pull request: 
- [x] checking whether generating a page using the `npm generate` command causes problems
- [x] new design from FIGMA
- [x] documentation of changes (commands, .env variables, etc.)
- [ ] updating docker file to run new page for developer view

### CODE REVIEW

**Comment by rosolowski** [comment]
https://github.com/edmcouncil/html-pages/pull/212 doesn't need to be implemented because the new figma project has a different list design anyway.

**Comment by mereolog** [comment]
The FIBO viewer main page (in the testing environment) opens very slowly (as of now).

**Comment by mereolog** [comment]
I think that the header is now too "high" - it takes up too much space.
image
Could we make it smaller (vertically)?

**Comment by mereolog** [comment]
Shouldn't the triangles in the FIBO menu drop-down be in the same direction as the one sin the domain drop-down list?
image

**Comment by mereolog** [comment]
For now, 'Data model' should read 'FIB-DM' - later we need to talk to Jurgen about that.
image

**Comment by mereolog** [comment]
FIBO Home has some left-overs:
image

**Comment by mereolog** [comment]
Also, I do not understand why there are three "new" sections there:
image

**Review by mereolog — CHANGES_REQUESTED** [review]
See my comments above.

**Comment by dasawanaka** [comment]
Aditional sections is removed now

**Comment by rosolowski** [comment]
https://github.com/edmcouncil/html-pages/pull/239#issuecomment-1221988528
> Shouldn't the triangles in the FIBO menu drop-down be in the same direction as the one sin the domain drop-down list? 
> ...

@mereolog in the figma project "dropdown menu" is presented as
image


There is only expanded state available for group items. So for collapsed I thought pointing the arrow towards content would make the most sense. 
It could be done as (2) where the arrow is on the left and behaves the same as in modules tree, but it looks like a lot of nesting - less readable.
It could be also done as (3) where the arrow is always pointing down, both when collapsed and expanded which looks clean.

image

**Comment by mereolog** [comment]
> [#239 (comment)](https://github.com/edmcouncil/html-pages/pull/239#issuecomment-1221988528)
> 
> > Shouldn't the triangles in the FIBO menu drop-down be in the same direction as the one sin the domain drop-down list?
> > ...
> 
> @mereolog in the figma project "dropdown menu" is presented as image
> 
> There is only expanded state available for group items. So for collapsed I thought pointing the arrow towards content would make the most sense. It could be done as (2) where the arrow is on the left and behaves the same as in modules tree, but it looks like a lot of nesting - less readable. It could be also done as (3) where the arrow is always pointing down, both when collapsed and expanded which looks clean.
> 
> image

Then leave it as it is now.

**Review by mereolog — DISMISSED** [review]

**Comment by patrycjamia** [comment]
Clicking on a node in the graph does not display the class, but returns an error:
image

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comment is above.

**Comment by mereolog** [comment]
There are differences between the "old" and the "new" outlook (snips taken from the testing environment):
- fonts
- sizes
- contents

**Old**
image

**New**
image

Why?

**Review by mereolog — CHANGES_REQUESTED** [review]
See my last comment above.

**Comment by mereolog** [comment]
> Clicking on a node in the graph does not display the class, but returns an error:
> image

It seems that this is fixed now.
@patrycjamia could you confirm?

**Comment by rosolowski** [comment]
> There are differences between the "old" and the "new" outlook (snips taken from the testing environment):
> 
> * fonts
> * sizes
> * contents
> 
> Why?

Font family and sizes were not changed. There are hovewer changes in spacing (for example, between headings and paragraphs, article horizontal margin size) so that full page articles have the same style as "How to use" article in new design.
The carousel content is from older version of IDMP I think, it can be changed in strapi.

**Comment by mereolog** [comment]
> > There are differences between the "old" and the "new" outlook (snips taken from the testing environment):
> > 
> > * fonts
> > * sizes
> > * contents
> > 
> > Why?
> 
> Font family and sizes were not changed. There are hovewer changes in spacing (for example, between headings and paragraphs, article horizontal margin size) so that full page articles have the same style as "How to use" article in new design. The carousel content is from older version of IDMP I think, it can be changed in strapi.

@rr-adam  Would you mind changing the carousel content before we merge this PR?

**Comment by rosolowski** [comment]
> > > There are differences between the "old" and the "new" outlook (snips taken from the testing environment):
> > > 
> > > * fonts
> > > * sizes
> > > * contents
> > > 
> > > Why?
> > 
> > 
> > Font family and sizes were not changed. There are hovewer changes in spacing (for example, between headings and paragraphs, article horizontal margin size) so that full page articles have the same style as "How to use" article in new design. The carousel content is from older version of IDMP I think, it can be changed in strapi.
> 
> @rr-adam Would you mind changing the carousel content before we merge this PR?

@mereolog I updated the carousel content in strapi just now. Change will be reflected whenever the branch is rebuilt/generated again.

**Comment by patrycjamia** [comment]
> > Clicking on a node in the graph does not display the class, but returns an error:
> > image
> 
> It seems that this is fixed now. @patrycjamia could you confirm?

Yes

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
