### PR TITLE
New gui design - required changes

### PR DESCRIPTION
**Pull request by dasawanaka**
### Changes:

- [x]  [fixed tree elements displaying in confusing way](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001515462) @rr-adam 
- [x] [made the spacing shorter](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001520015) @rr-adam 
- [x]  [removed first letter capitalization from label](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001549901) @rr-adam 
- [x]  [changed "See more..." to the "Show more" button with arrow](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001554525) @rr-adam 
- [x]  [changed font size for paths](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001559036) @rr-adam 
- [x] [reduced empty spaces between results](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001608912) @rr-adam 
- [x]  [indicator  should be rotated (clockwise) ](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001556858) @dasawanaka 
- [x] [copyright - update date](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001557805) @dasawanaka 
- [x] [FIBO VIEWER > FIBO Viewer ](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001567243) @dasawanaka 
- [x] [formatting the home page according to requirements ](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001574729) @dasawanaka 
- [x] [the layout of the elements is very dispersed and looks strange](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001588977) (inline with title? @patrycjamia) 
- [x] [problem with displaying links in new lines](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001593288)  (resolution, zoom when problem occurs? @patrycjamia)  
I don't know what steps to take to solve this, if any, reduce the font size to a smaller size or increase the area on the right if possible, this is up for discussion. @mereolog 
- [x] [graph colors changes](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001595990) @dasawanaka 
- [x] [search placeholder text](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001611505) @dasawanaka 
- [x] [width of the search bar](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001619218) @dasawanaka 
- [x]  [Fibo -> FIBO](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003934528) @dasawanaka 
- [x] [Result count is always "1234"](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003932130) reply: [comment](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003963428)
- [x] [Search, version dropdown look difrent](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003941173) @rr-adam 
- [x]  [Some groups is not collapsed by default](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003955279) @rr-adam 
- [x] repair strange graph display when node has long label @dasawanaka 
- [x] [multiselect burger hide down arrow](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1011982744) 
- [x] [urls in search results are not hyperlinks](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1012008566)

[Group 'other'](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001552628) depends on json from backend, frontend does not change group elements or order.

**Please check mobile version.**

### CODE REVIEW

**Comment by mereolog** [comment]
All my comments from #109 were addressed except for https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001574729 and https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001552628.

**Comment by mereolog** [comment]
All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.

**Comment by mereolog** [comment]
We should be consistent in using the acronym for FIBO.
The viewer's landing page (fibo/ontology) shows two acronyms: FIBO and Fibo:
image
@dasawanaka please make sure that we display "FIBO" across all pages in this project.

**Comment by mereolog** [comment]
It seems to me that the search display looks different than in the figma mockup.
**figma**
image
**implementation**
image

**Comment by mereolog** [comment]
When I open /fibo/ontology/BP/SecuritiesIssuance/DebtIssuance/, the list of internal classes is collapsed, as required, but the list of external classes is not.
image

**Comment by dasawanaka** [comment]
> All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.

prod application has been updated with the changes required for this and is it publicly available?  
PR from https://github.com/edmcouncil/onto-viewer/pull/139 is merged but it used on prod/dev servers to test it with GUI?

**Comment by mereolog** [comment]
> > All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.
> 
> prod application has been updated with the changes required for this and is it publicly available? PR from [edmcouncil/onto-viewer#139](https://github.com/edmcouncil/onto-viewer/pull/139) is merged but it used on prod/dev servers to test it with GUI?

Our "remote" testing environment runs onto-viewer from commit 4c2ae5cf531c8c4dc465a081218c48d1c540b39c, so the changes should be accessible from there. And the problem reported occurs also in the testing environment.

**Comment by rosolowski** [comment]
> > > All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.
> > 
> > 
> > prod application has been updated with the changes required for this and is it publicly available? PR from [edmcouncil/onto-viewer#139](https://github.com/edmcouncil/onto-viewer/pull/139) is merged but it used on prod/dev servers to test it with GUI?
> 
> Our "remote" testing environment runs onto-viewer from commit 4c2ae5cf531c8c4dc465a081218c48d1c540b39c, so the changes should be accessible from there. And the problem reported occurs also in the testing environment.

1234 is a hard coded value used as a placeholder in the old API. I just made a commit where it should use the new API if "totalResult" value exists, if not it will still show 1234.

**Comment by dasawanaka** [comment]
> 1234 is a hard coded value used as a placeholder in the old API. I just made a commit where it should use the new API if "totalResult" value exists, if not it will still show 1234.

If "totalResult" does not occur it seems better to display 0, what number do you display when there are no search results? This may be misleading information

**Comment by mereolog** [comment]
> > > > All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.
> > > 
> > > 
> > > prod application has been updated with the changes required for this and is it publicly available? PR from [edmcouncil/onto-viewer#139](https://github.com/edmcouncil/onto-viewer/pull/139) is merged but it used on prod/dev servers to test it with GUI?
> > 
> > 
> > Our "remote" testing environment runs onto-viewer from commit 4c2ae5cf531c8c4dc465a081218c48d1c540b39c, so the changes should be accessible from there. And the problem reported occurs also in the testing environment.
> 
> 1234 is a hard coded value used as a placeholder in the old API. I just made a commit where it should use the new API if "totalResult" value exists, if not it will still show 1234.

Btw., the current backend does return the number of results:
```
"query": "tax",
    "page": 1,
    "hasMore": true,
    "maxPage": 9,
    "totalResut": 86
}
```

**Comment by rosolowski** [comment]
> > > > > All queries show the same number of results, i.e., "1234" - check out for example fibo/ontology?searchBoxQuery=school and fibo/ontology?searchBoxQuery=tax.
> > > > 
> > > > 
> > > > prod application has been updated with the changes required for this and is it publicly available? PR from [edmcouncil/onto-viewer#139](https://github.com/edmcouncil/onto-viewer/pull/139) is merged but it used on prod/dev servers to test it with GUI?
> > > 
> > > 
> > > Our "remote" testing environment runs onto-viewer from commit 4c2ae5cf531c8c4dc465a081218c48d1c540b39c, so the changes should be accessible from there. And the problem reported occurs also in the testing environment.
> > 
> > 
> > 1234 is a hard coded value used as a placeholder in the old API. I just made a commit where it should use the new API if "totalResult" value exists, if not it will still show 1234.
> 
> Btw., the current backend does return the number of results:
> 
> ```
> "query": "tax",
>     "page": 1,
>     "hasMore": true,
>     "maxPage": 9,
>     "totalResut": 86
> }
> ```

Looks like there's a typo in totalResult variable name, should be "totalResult" according to [rest api documentation](https://github.com/edmcouncil/onto-viewer/blob/develop/api-doc/rest_api.md#3-text-search). The number 86 is returned correctly, just the name doesn't match.
I made the frontend to look for "totalResut" instead in the latest commit.

**Comment by rosolowski** [comment]
@patrycjamia Based on [the layout of the elements is very dispersed and looks strange](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001588977) comment
I made the following changes:

if the button can fit next to the title (with some margin) it will display inline
maturityLevel_none

if maturity level alert is present, the report problem button will behave the same as before
maturityLevel_exists

**Comment by mereolog** [comment]
b29644541c463de2f6307f4f8806f76b7ad46bfb didn't fix https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003932130.
Now the query produces this:
image

**Comment by rosolowski** [comment]
> [b296445](https://github.com/edmcouncil/html-pages/commit/b29644541c463de2f6307f4f8806f76b7ad46bfb) didn't fix [#110 (comment)](https://github.com/edmcouncil/html-pages/pull/110#issuecomment-1003932130). 

The problem should be fixed in the latest commit

**Comment by patrycjamia** [comment]
> * [ ]  [problem with displaying links in new lines](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001593288)  (resolution, zoom when problem occurs? @patrycjamia)
>       I don't know what steps to take to solve this, if any, reduce the font size to a smaller size or increase the area on the right if possible, this is up for discussion. @mereolog

Links move strangely to the new line. There was a time when there was talk of changing the text with a link into a real hyperlink on the backend. e.g. the text https://spec.edmcouncil.org/fibo/ontology/IND/MarketIndices/BasketIndices.rdf
displayed as BasketIndices.rdf (URL ending).

**Comment by patrycjamia** [comment]
> * [the layout of the elements is very dispersed and looks strange](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001588977) (inline with title? @patrycjamia)

It looks better now.

**Comment by patrycjamia** [comment]
> @patrycjamia Based on [the layout of the elements is very dispersed and looks strange](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001588977) comment I made the following changes:
> 
> if the button can fit next to the title (with some margin) it will display inline maturityLevel_none
> 
> if maturity level alert is present, the report problem button will behave the same as before maturityLevel_exists

It looks better now.

**Comment by mereolog** [comment]
> > * [ ]   [problem with displaying links in new lines](https://github.com/edmcouncil/html-pages/pull/109#issuecomment-1001593288)  (resolution, zoom when problem occurs? @patrycjamia)
> >   I don't know what steps to take to solve this, if any, reduce the font size to a smaller size or increase the area on the right if possible, this is up for discussion. @mereolog
> 
> Links move strangely to the new line. There was a time when there was talk of changing the text with a link into a real hyperlink on the backend. e.g. the text https://spec.edmcouncil.org/fibo/ontology/IND/MarketIndices/BasketIndices.rdf displayed as BasketIndices.rdf (URL ending).

Since these links are in annotations, I would leave them as they are, at least for now.

**Comment by mereolog** [comment]
For some classes the local id of the class is displayed instead of the label:
image
In the example below we should display 'loan pool' and not LoanPool.

**Comment by mereolog** [comment]
The banner displays a small triangle close to the "hamburger":
image

**Review by mereolog — CHANGES_REQUESTED** [review]
Required changes are mentioned in earlier comments.

**Comment by mereolog** [comment]
> For some classes the local id of the class is displayed instead of the label:
> image
> In the example below we should display 'loan pool' and not LoanPool.

This issue does not occur in the testing environment.

**Comment by patrycjamia** [comment]
Urls in search results are not hyperlinks. 

image

**Comment by patrycjamia** [comment]
I would change the colour or add a hover effect in the hyperlinks (throughout the ontology view)

**Comment by dasawanaka** [comment]
> For some classes the local id of the class is displayed instead of the label: image In the example below we should display 'loan pool' and not LoanPool.

The value is returned from the backend in this field. The backend should return the appropriate value.

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comments are above.

**Comment by mereolog** [comment]
There are two icons used for 'Show more': "triangle" and "magnifying glass" , see e.g., /fibo/ontology/LOAN/LoanContracts/LoanCore/Loan:

image

**Comment by mereolog** [comment]
@rr-adam would it be a problem to apply the "magnifying glass" all over the place?
(I like it better than the triangle :).)

Apologies for not being clear about it.

**Comment by rosolowski** [comment]
> @rr-adam would it be a problem to apply the "magnifying glass" all over the place? (I like it better than the triangle :).)
> 
> Apologies for not being clear about it.

No problem! What about the collapse icon, should it be magnifying glass or should I keep the triangle there?

**Comment by mereolog** [comment]
> > @rr-adam would it be a problem to apply the "magnifying glass" all over the place? (I like it better than the triangle :).)
> > Apologies for not being clear about it.
> 
> No problem! What about the collapse icon, should it be magnifying glass or should I keep the triangle there?

Do the magnifying glass, please.

**Comment by rosolowski** [comment]
> > > @rr-adam would it be a problem to apply the "magnifying glass" all over the place? (I like it better than the triangle :).)
> > > Apologies for not being clear about it.
> > 
> > 
> > No problem! What about the collapse icon, should it be magnifying glass or should I keep the triangle there?
> 
> Do the magnifying glass, please.

I updated the icons, let me know if I should change anything.

**Review by mereolog — APPROVED** [review]

**Comment by patrycjamia** [comment]
Iri in search, which is a hyperlink, would look better if it was underlined. Just like it is in the module tree to make the links on the page consistent.

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comment is above.

**Review by mereolog — APPROVED** [review]

**Comment by patrycjamia** [comment]
@rr-adam Hyperlinks are permanently underlined. And there are supposed to be underlined only when you hover over a link, as is the case with the module tree. The other elements look correct.

**Review by patrycjamia — CHANGES_REQUESTED** [review]
My comment is above.

**Comment by patrycjamia** [comment]
image
I think that the justified text that is in a glossary, summary, note, description etc will look better.

**Review by mereolog — CHANGES_REQUESTED** [review]
When I ran the latter commit in Docker, i.e., locally, the 'Show less' button is no longer clickable.

image

Oddly enough in other places it seems to work:

image

**Review by patrycjamia — APPROVED** [review]

**Review by mereolog — APPROVED** [review]

**Pull request merged**
