### PR TITLE
Ontoviewer diagram legend

### LINKED ISSUE #273: Ontoviewer diagram legend
The graph should have explanations for conventions used in it.

### PR DESCRIPTION
**Pull request by rosolowski**
closes: #273 

Added "User Guide" button in graph section and in the graph control panel. The button opens guide window:

image

The guide is split into 4 pages: 

- Basics - opens by default
- Connections - describes different connection types and their visual representation
- Layouts - describes available layouts and usage
- Sorting - describes each sorting type

The guide contains images, when user hovers on image it zooms into place that is being described in the section.

### CODE REVIEW

**Comment by dasawanaka** [comment]
For me buttons with other sections/sites on bottom bar is not good for user experience, for me this buttons(on bottom bar inline with close button) looks like navigations button and i dont see diffrences on buttons with other sections and close. 

Maybe can we make small menu on top of manual or move buttons to top bar? 

If 'menu' be on top, good option is add button go to top for easiest navigation.

Under text basic manual page we can add links to other manual pages, something like 'see also'. In this case if somebody does't see buttons or other navigation still can go to other manual sections after reading this section.

I leave my comment for discussion for other team members.

**Comment by mereolog** [comment]
> For me buttons with other sections/sites on bottom bar is not good for user experience, for me this buttons(on bottom bar inline with close button) looks like navigations button and i dont see diffrences on buttons with other sections and close.
> 
> Maybe can we make small menu on top of manual or move buttons to top bar?
> 
> If 'menu' be on top, good option is add button go to top for easiest navigation.
> 
> Under text basic manual page we can add links to other manual pages, something like 'see also'. In this case if somebody does't see buttons or other navigation still can go to other manual sections after reading this section.
> 
> I leave my comment for discussion for other team members.

I agree with @dasawanaka as far as the issue he spotted is concerned.

**Review by mereolog — CHANGES_REQUESTED** [review]
See my comment above.

**Comment by rosolowski** [comment]
Added table of contents to all pages as seen below and removed navigation buttons from footer.

image

**Review by mereolog — APPROVED** [review]

**Review by dasawanaka — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
