### PR TITLE
Add Describe button to front-end

### LINKED ISSUE #315: Add Describe button to front-end
Add describe feature using the endpoint below.
https://github.com/edmcouncil/onto-viewer/blob/develop/api-doc/INTEGRATION.md

### PR DESCRIPTION
**Pull request by rosolowski**
closes: #315 

Added Describe button to resource header:
image

If result is available it opens window with content:
image

If integration is not configured on the server or an error was encountered, the button is greyed out:
image

### CODE REVIEW

**Comment by mereolog** [comment]
@rr-adam , since we do not collect any actual RDF content for the ontologies themselves, would it be possible not to display this button on such pages as https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11240-UnitsOfMeasurement/?

**Comment by mereolog** [comment]
@rr-adam can we have a text like 'Back to main page' or similar instead of:

image

IMHO the current text may be misleading.

**Comment by mereolog** [comment]
On macOS 12.5.1 (Safari, Chrom) the copy button does not work, i.e., nothing is copied to the clipboard:
image
Also, @rr-adam  could we have 'Copy' instead of 'Copy code'?

**Comment by rosolowski** [comment]
@mereolog I introduced the changes you mentioned along with other updates:

Resource header redesign - added "show more" dropdown:
image

Changed the text next to return arrow to "return" instead of window title, changed copy button text to "copy", changed content font to "Roboto Mono":
image

**Comment by mereolog** [comment]
> @mereolog I introduced the changes you mentioned along with other updates:
> 
> Resource header redesign - added "show more" dropdown: image
> 
> Changed the text next to return arrow to "return" instead of window title, changed copy button text to "copy", changed content font to "Roboto Mono": image

@rr-adam thanks, but note the the build of the last commit failed.

**Review by mereolog — COMMENTED** [review]
Looks great, but I have two comments about the three dots char:
image

1. It looks to me too small if you compare it the main heading.
2. Shouldn't it be horizontal and not vertical - see, for example, https://uxpickle.com/significance-of-the-three-dots-or-ellipses-in-ui-design/?

**Comment by rosolowski** [comment]
> Looks great, but I have two comments about the three dots char: 
> 1. It looks to me too small if you compare it the main heading.
> 2. Shouldn't it be horizontal and not vertical - see, for example, https://uxpickle.com/significance-of-the-three-dots-or-ellipses-in-ui-design/?

I think vertical or horizontal is a matter of preference, for example in Google apps (Chrome, Gmail, YouTube etc) and Android vertical "kebab menu" is used a lot but in Microsoft apps (Edge, Outlook, Teams etc) they have horizontal dots for the same use cases.

This is how the header would look like with the dropdown icon being 40x40px instead of the current 24x24px with horizontal and vertical dots:

image

@mereolog Let me know which option makes more sense to you.

**Comment by mereolog** [comment]
> > Looks great, but I have two comments about the three dots char:
> > 
> > 1. It looks to me too small if you compare it the main heading.
> > 2. Shouldn't it be horizontal and not vertical - see, for example, https://uxpickle.com/significance-of-the-three-dots-or-ellipses-in-ui-design/?
> 
> I think vertical or horizontal is a matter of preference, for example in Google apps (Chrome, Gmail, YouTube etc) and Android vertical "kebab menu" is used a lot but in Microsoft apps (Edge, Outlook, Teams etc) they have horizontal dots for the same use cases.
> 
> This is how the header would look like with the dropdown icon being 40x40px instead of the current 24x24px with horizontal and vertical dots:
> 
> image
> 
> @mereolog Let me know which option makes more sense to you.

Let's go for horizontal then.

**Comment by rosolowski** [comment]
The button is now 40x40px and horizontal:
image

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
