### PR TITLE
Display all references to the deprecated resource in a different way

### LINKED ISSUE #350: Display all references to the deprecated resource in a different way
When a resource is deprecated all references to it should be somehow highlighted - perhaps in red, for example, the reference to https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/ActiveIngredientRole on https://spec.pistoiaalliance.org/idmp/ontology/ISO/ISO11238-Substances/ should be hightlighted.

### PR DESCRIPTION
**Pull request by dasawanaka**
Resolve: #350 

## Prepared examples of hightlighting:

1. color: basic, line-through
basic line-through

2.  color: basic, 2 lines
basic two lines

3. color: ff6000, underline
color ff6000

4. color: ff6000, underline, thickness: 15%
color ff6000 thickness 15

5. color: red, underline
color red

6. color: red, underline, thickness: 15%
color red thickness 15

7. color: ff6000, line-through
ff6000 line-through

8. color: red, line-through
red thoughline

9. color: basic, underline, decor color: ff6000
text-decoration-color ff6000

10. color basic, underline, decor color: red
text-decoration-color red

11. color basic, line-through, decor color: ff6000
image

12. color: basic, line-through, decor color: red
red line-through

## Example for axioms
anotherExampleInAxioms

### CODE REVIEW

**Comment by mereolog** [comment]
I vote for 8.

**Comment by dasawanaka** [comment]
Additional with color #EC241D insted of red:

13. underline, color, decor color
ec241d-color-dec-color-underline

14. underline, decor color
ec241d-underline-color

15. line-through, decor color
ec241d line-through

16. line-through,  color, decor color
ec241d-color-dec-color-line-through

**Comment by dasawanaka** [comment]
16`. Example for axiom: 
image

**Comment by rosolowski** [comment]
For me 13 and 16 look good

**Comment by mereolog** [comment]
16.

**Review by mereolog — APPROVED** [review]

**Review by rosolowski — APPROVED** [review]

**Pull request merged**
