### PR TITLE
Displays flag icons instead of language tags

### PR DESCRIPTION
**Pull request by dasawanaka**
Signed-off-by: dasawanaka <michal.19.daniel.96@gmail.com>

Issue: #104 

prev pr: #117

### CODE REVIEW

**Comment by dasawanaka** [comment]
Which flag we should display on latin language?

[comment](https://github.com/edmcouncil/html-pages/pull/117#issuecomment-1039096402)

**Comment by patrycjamia** [comment]
Still no flags mentioned in:
https://github.com/edmcouncil/html-pages/pull/117#issuecomment-1028943569

**Review by patrycjamia — DISMISSED** [review]

**Comment by mereolog** [comment]
On macOS 12.0.1 I run these:
`docker-compose --profile=fibo build`
`docker-compose --profile fibo up -d`
and got this error:
```
yarn run v1.22.17
$ vue-cli-service serve
 INFO  Starting development server...
<s> [webpack.Progress] 0% compiling
<s> [webpack.Progress] 10% building 0/0 modules 0 active 
...
<s> [webpack.Progress] 98% after emitting CopyPlugin
 ERROR  Failed to compile with 1 error9:19:49 AM

Syntax Error: TypeError: eslint.CLIEngine is not a constructor
```

**Review by mereolog — CHANGES_REQUESTED** [review]
@dasawanaka please resolve the merge conflict(s).

**Comment by dasawanaka** [comment]
> and got this error

What version of docker do you have? 

```
docker --version
Docker version 20.10.11, build dea9396
```

**Comment by mereolog** [comment]
> > and got this error
> 
> What version of docker do you have?
> 
> ```
> docker --version
> Docker version 20.10.11, build dea9396
> ```

Docker version 20.10.8, build 3967b7d

**Comment by mereolog** [comment]
Something is lurking behind the language flag:

image

**Comment by mereolog** [comment]
Since EDMC is US-based, I think that the 'en' tag should resolve into the American flag.

**Comment by mereolog** [comment]
The language tag "en-us" should resolved into the American flag.
image

**Comment by mereolog** [comment]
The "en-gb" language tag resolves into a flag and '-gb' string:
image

**Comment by mereolog** [comment]
The "ex-mx" language tag should resolve into the flag of Mexico.


image

**Review by mereolog — CHANGES_REQUESTED** [review]
My review comments are above.

**Comment by dasawanaka** [comment]
> The language tag "en-us" should resolved into the American flag.

 `en-us`  is not a valid lang according to [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) (this solution is currently prepared for it). We do not support the [IETF](https://en.wikipedia.org/wiki/IETF_language_tag) where it is correct.

**Comment by mereolog** [comment]
> > The language tag "en-us" should resolved into the American flag.
> 
> `en-us` is not a valid lang according to [ISO 639-1](https://en.wikipedia.org/wiki/ISO_639-1) (this solution is currently prepared for it). We do not support the [IETF](https://en.wikipedia.org/wiki/IETF_language_tag) where it is correct.

Fair enough, then do not resolve 'en-us' at all, i.e., leave it as a string.
Similarly for other 'composite' language tags.

**Review by mereolog — APPROVED** [review]

**Review by patrycjamia — APPROVED** [review]

**Pull request merged**
